# Generated by Django 5.2.7 on 2025-10-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherjson',
            name='teacher_address',
            field=models.CharField(default='noaddress', max_length=255),
        ),
        migrations.AddField(
            model_name='teacherjson',
            name='teacher_email',
            field=models.EmailField(default='example@email.com', max_length=100),
        ),
        migrations.AddField(
            model_name='teacherjson',
            name='teacher_password',
            field=models.CharField(default='password123', max_length=100),
        ),
        migrations.AddField(
            model_name='teacherjson',
            name='teacher_phone',
            field=models.CharField(default='0000000000', max_length=15),
        ),
    ]
